#server:
#  port: 9002
#
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/microserv?useSSL=false
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#  application:
#    name: order-service
#  zipkin:
#    base-url : http://localhost:9411
#  sleuth:
#    sampler:
#      probability : 1.0
##logging:
##  level:
##    org:
##      hibernate:
##        SQL: DEBUG
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
#
#management:
#  health:
#    circuit-breakers:
#      enabled: true
#  endpoints:
#    web:
#      exposure:
#        include: *
#  endpoint:
#    health:
#      show-details: always
#
### Resilience Properties
#resilience4j:
#  circuit-breaker:
#    instances:
#      inventory:
#        registerHealthIndicator: true
#        event-consumer-buffer-size: 10
#        slidingWindowType: COUNT_BASED
#        slidingWindowSize: 5
#        failureRateThreshold: 50
#        waitDurationInOpenState: 5s
#        permittedNumberOfCallsInHalfOpenState: 3
#        automaticTransitionFromOpenToHalfOpenEnabled: True
#
